params:
  seed: ${...seed}
  algo:
    name: a2c_continuous  # PPO 알고리즘을 사용

  model:
    name: continuous_a2c_logstd  # PPO용 연속형 모델 사용

  network:
    name: actor_critic
    separate: False

    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    mlp:
      units: [256, 128, 64]
      activation: elu
      d2rl: False

      initializer:
        name: default
      regularizer:
        name: None

  load_checkpoint: ${if:${...checkpoint},True,False} # 체크포인트 로드 여부
  load_path: ${...checkpoint} # 체크포인트 경로

  config:
    name: ${resolve_default:FrankaPickAndPlace,${....experiment}}
    full_experiment_name: ${.name}
    env_name: rlgpu
    device: ${....rl_device}
    device_name: ${....rl_device}
    multi_gpu: ${....multi_gpu}
    ppo: True
    mixed_precision: False
    normalize_input: True
    normalize_value: True
    num_actors: ${....task.env.numEnvs}
    reward_shaper:
      scale_value: 0.01
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    learning_rate: 5e-4
    lr_schedule: adaptive
    kl_threshold: 0.008
    score_to_win: 100000000
    max_epochs: ${resolve_default:1500,${....max_iterations}}
    save_best_after: 200
    save_frequency: 100
    print_stats: True
    grad_norm: 1.0
    entropy_coef: 0.01  # 엔트로피 계수는 적당히 설정하여 탐색을 장려
    truncate_grads: True
    e_clip: 0.2
    horizon_length: 32  # Horizon length를 조정하여 더 긴 기간 동안 학습
    minibatch_size: 8192
    mini_epochs: 10  # Mini-batch에 대한 학습 횟수를 늘려 정확성 향상
    critic_coef: 2.0  # Critic loss 계수 조정
    clip_value: True
    seq_length: 4
    bounds_loss_coef: 0.0001

